version: '3.2'
services:
    mongo:
        image: mongo
        volumes: 
            - mongo-data-spring:/data/db

    spring:
        build:
            context: .
        ports: 
            - 8080:8080
        environment: 
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - MONGO_DATABASE=spring-apiman
        depends_on: 
            - mongo

volumes:
    mongo-data-spring: